### ISSUE TITLE
Allow to run in local network without internet

### ISSUE THREAD

**Issue by Gbury** [SimonKinds/4temps-tournament#128] opened 2018-03-06 11:46 UTC
Currently the CSS style sheets seems to be hosted on cloudfare, which effectively makes the site very ugly when run on a local network without internet access. While that alone can be fixed easily (which we did in a hurry when setting up the tournament), it seems the CSS itself also performs some internet access (I remember seeing some queries to some google fonts) which unnecessarily slowed the pages during the competition.

How hard would it be to make everything work in networks with no internet access (either by removing the internet access or serving all ressources locally) ?

**Comment by SimonKinds** [comment] 2018-03-06 12:43
# Answer
We're using [Semantic UI (React)](https://react.semantic-ui.com/) to get good looking components with little effort. In their [usage section](https://react.semantic-ui.com/usage) they explain how to bundle it locally and not use a CDN. I don't know if this also includes the fonts from google fonts. 

# Follow up
I was not aware that you would be running offline during the competition, which I why I didn't consider this to be an issue. 

# What environments are we expecting the website to be accessed in?
I expected the admin and judges to have an internet connection. This turned out to not be true.

Should we even expect a bad connection from users to a locally hosted version? From what I've understood, this was also the case during the tournament. MM mentioned something about groups not being generated in time, which should only be possible if the judges have not submitted. Which should only be a problem if they _can't_.

If the app is supposed to be run with a spotty connection some other design considerations have to be made, such as optimistic UI updates after a network request, not waiting for responses. 

One could also look into service-workers to make the app better when offline.

As I am not a user of this website, I don't know what you, _the users_, want or expect.
**My question is**, what kind of environment are we expecting?

Also, this issue seems contradictory to your comment regarding email-providers. As email would only ever be needed if it's hosted online. Email would only be used for email-reset, which the one hosting the website locally could perform manually.

# Lastly
I welcome any contributions, please let me know if you need some help getting started.

**Comment by Gbury** [comment] 2018-03-06 15:18
All right, sorry for the communication problems.

## Actual setup used

So last Saturday, the setup was the following: each judge had a tablet to use and connect to the judging site, MM brought her laptop for the server to run on, and I brought my wifi router. I gave a static IP address to the laptop, and everyone connected to the router. The router effectively only served to connect the tablets to the laptop.

## Expected conditions for upcoming events

Basically, we can't really expect to always have a reliable internet uplink at upcoming events where we might want to use the judging system. I think the usual setup will be the following: each judge has a device (phone/tablet/personal laptop). There is a wifi network (either provided by the venue, or generated by a router brought specifically for the occasion) but no guaranteed internet access. The staff for the event brings a laptop to host the server locally.

It might be possible to have internet access (though not always), but it would typically be through a shared 3G/4G connection, with limited bandwidth/high latency, so I think it is best if the default is for the system to run locally, without needing internet access.

I think the wifi connection was fine last saturday. What made the connection appear spotty was the CSS queries to content on the internet, indeed when loading the CSS, the browser would try and fetch the content but fail: the query (probably the DNS request) would timeout (and I guess a fallback solution would be used), and that means that every page would take something like 10 seconds to load, wile actually the main content (i.e. the js script) was downloaded instantly, but the rendering waited on the CSS queries. Just to be safe, I'll look into having some wifi repeaters (or a more powerful router, after all we used my personal home router, which is now a bit old and not really designed to extend very far) for next events.

## Expect server load

What do you expect would be the server load of running the server ? More specifically, do you think it would be possible for it to run reasonably well on something like a raspberry pi ? I'm thinking about building some kind of tournament box that would include a raspberry pi and a small wifi router, ideally so that it can be transported, plugged in, and run directly.

## About email

You're right about me being inconsistent, ^^
I was just reading the open issues and thought using an external service might be more complex than a local implementation, but I was probably wrong.

## Contributing

Sure I'll try and contribute, but I'm currently mostly used to academic (i.e. theoretical research) programs written in ocaml, so give me some time to get used to real world js code, :p

**Comment by SimonKinds** [comment] 2018-03-06 15:39
No need for apologies, you didn't know what I knew or did not know.

Thanks for letting me know about the setup. It's a bummer you had to go through that, I wish I knew the environment beforehand to alleviate any such issues.

The website is supposed to be able to update in real-time without any refresh, did that not happen? Or were there only issues during refresh e.g. when someone visited the website after closing the browser?

The expected server load should be low. It's almost exclusively a CRUD backend, major computations only occurring during group generation. Any crucial operations (such as taking attendance or taking notes) shouldn't have any issues to keep a low latency. It could probably be run on a Raspberry Pi 2B, but I can't say for sure. I suggest testing it out to be sure.

Don't worry about being inconsistent, having an online version and a local version doesn't have to be mutually exclusive.

**Comment by mmPaumard** [comment] 2018-03-06 15:42
We decided the setup two days before the tournament ^^'

The realtime refresh happen; however, as the connection was slow, I told the judges to press refresh (so they feel they are waiting for something rather than just thinking nothing is happening) :)

**Comment by SimonKinds** [comment] 2018-03-06 16:04
I was not certain how things actually turn out in case of bad connectivity etc, so I just simulated it by connecting to a hotspot on my phone but turning of mobile data. This should simulate the same situation as during the tournament, with a local network without internet.

I too, experienced a ~10sec delay before the website was shown. I confirmed this to be because of domain name lookup.
I then tried the real-time update, because I felt it should be responsive as long as the local network is OK.

And yes, the real-time update was fine as long as the network was reliable. So my guess why the website felt unresponsive was due to connection issues within the local network. A possible, but less likely reason, would be that MM's laptop was overloaded. I don't see this happening though.

An example of the real-time updates being quick without internet connectivity can be seen below.
![gif](https://thumbs.gfycat.com/ThirstyMediumBluet-size_restricted.gif)

**Comment by Gbury** [comment] 2018-03-06 17:20
Ok, weak wifi was indeed probably one of our problems, so thinking about how to have a better setup for future events, I see two possibilities:
- server laptop + big wifi router (mine is about 7 years old, new routers have shiny antennas for better range) in order to have good reception even far away, this setup can live midway between the judges and the staff taking attendance (since the router has good range).
- raspberry pi server (pending a test to verify it works) + small wifi card, in this case, the setup is small enough it can fit in a nice little box, and thus can be located next to the judges, hence no need for a big range for the wifi. In that case, there's still the little problem that the staff taking attendance might be far away from the judges' table and thus don't have good connection. For that I see two possible solutions: 
  * have some wifi extender connected by ethernet to the raspberry pi, or directly connect the staff laptop by ethernet with a long enough cable, or
  * assuming a strict deadline on registration (let's be hopeful), we could simply first plug the box next to the registration table, and then move it to the judges' table (or have the registration table and the judges' table next to another, but it's not always possible).

@mmPaumard any comment / preference for any of the setups ?

**Closed** 2018-03-21 19:29 UTC
Labels: enhancement, question
